spring:
  application:
    name: 'customer-product'
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog.yaml"
